const DRUGS = window.PERIOP_DRUGS || [];
const $ = id => document.getElementById(id);
let currentView = 'commonWorkflow';
let currentCategory = 'all';
let visibleRows = [];

const CLASS_COLORS = {
  'Common': 'common','Hypnotic': 'hypnotic','Sedative': 'sedative','Opioid': 'opioid','Neuromuscular blocker': 'nmb','Reversal/rescue': 'reversal','Pressor/inotrope': 'pressor','Antihypertensive/vasodilator': 'vasodilator','Antiemetic/GI': 'antiemetic','Analgesic adjunct': 'analgesic','Local anesthetic': 'local','Regional adjunct': 'regional','Volatile/inhaled': 'volatile','Antibiotic': 'antibiotic','Coagulation/reversal': 'coag','Electrolyte/metabolic': 'electrolyte','OB uterotonic': 'ob','Pulmonary': 'pulmonary','Neuro/rescue': 'neuro','Steroid/endocrine': 'steroid','Fluid/blood adjunct': 'fluid','Rescue/other': 'other'
};
const STAGE_ORDER = ['Induction/sedation','Maintenance/volatile','Analgesia/opioids','Paralysis/reversal','Hemodynamics','PONV/aspiration','Regional/neuraxial','Coagulation/blood','Metabolic/rescue','OB','Antibiotics','Other/rescue'];
function round(x){if(!Number.isFinite(x))return'';const ax=Math.abs(x);if(ax>=100)return Math.round(x).toString();if(ax>=10)return(Math.round(x*10)/10).toString();if(ax>=1)return(Math.round(x*100)/100).toString();return(Math.round(x*1000)/1000).toString();}
function practical(x,unit){if(!Number.isFinite(x))return'';let step=1;if(unit.includes('mcg')){if(x>=1000)step=100;else if(x>=100)step=25;else if(x>=10)step=5;else step=1;}else if(unit.includes('mg')){if(x>=500)step=50;else if(x>=100)step=10;else if(x>=20)step=5;else if(x>=5)step=1;else step=0.1;}else if(unit.includes('unit')){step=x>=10?5:1;}else{step=x>=10?1:0.1;}return round(Math.round(x/step)*step);}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function patient(){const sex=$('sex').value,age=Number($('age').value),h=Number($('height').value),w=Number($('weight').value),scr=Number($('scr').value);const inches=h/2.54,over=Math.max(0,inches-60);const ibw=Math.max(1,(sex==='male'?50:45.5)+2.3*over);const bmi=w/((h/100)**2);const lbw=sex==='male'?(9270*w)/(6680+216*bmi):(9270*w)/(8780+244*bmi);const adjbw=ibw+0.4*Math.max(0,w-ibw);const bsa=Math.sqrt(h*w/3600);const crcl=((140-age)*w*(sex==='female'?0.85:1))/(72*Math.max(scr,0.1));return{sex,age,h,w,scr,ibw,lbw,adjbw,bsa,bmi,crcl,ef:Number($('ef').value),renal:$('renal').value,hepatic:$('hepatic').value,frail:$('frail').checked,osa:$('osa').checked,pregnant:$('pregnant').checked,qt:$('qt').checked,mh:$('mh').checked,shock:$('shock').checked,neuraxial:$('neuraxial').checked};}
function scalarWeight(p,scalar){if(scalar==='ABW')return p.w;if(scalar==='IBW')return p.ibw;if(scalar==='LBW')return p.lbw;if(scalar==='AdjBW')return p.adjbw;return null;}
function rangeText(a,b){return(b===undefined||a===b)?round(a):`${round(a)}-${round(b)}`;}
function practicalRange(a,b,unit){return(b===undefined||a===b)?practical(a,unit):`${practical(a,unit)}-${practical(b,unit)}`;}
function outUnit(unit){return unit.split('/')[0].replace(' fixed','');}
function macAge(mac40,age){return mac40*Math.pow(10,-0.00269*(age-40));}
function calcOne(dose,p,override){const scalar=override==='asWritten'?(dose.scalar||'Titrated'):override;const unit=dose.unit||'';const wt=scalarWeight(p,scalar);const mn=Number(dose.min??0),mx=Number(dose.max??mn);if(unit==='MAC_age'){const mac=macAge(mn,p.age);const vals=[0.5,0.7,1.0,1.3].map(m=>`${m} MAC ${round(mac*m)}% ET`).join('\n');return{scalar:'Age MAC',text:vals,rounded:`1 MAC ${practical(mac,'%')}% ET`,math:`MAC_age = MAC40 ${round(mn)} x 10^(-0.00269 x (${round(p.age)} - 40))`};}if(unit==='custom')return{scalar:'Custom',text:dose.label,rounded:'see protocol',math:'protocol/lab/indication dependent'};if(unit==='titrated')return{scalar:'Titrated',text:dose.label,rounded:'titrate',math:'titrate to clinical effect'};if(['mg/kg','mcg/kg','g/kg','mEq/kg','units/kg','mL/kg'].includes(unit)&&wt){const a=mn*wt,b=mx*wt;return{scalar,text:`${rangeText(a,b)} ${outUnit(unit)}`,rounded:`${practicalRange(a,b,outUnit(unit))} ${outUnit(unit)}`,math:`${rangeText(mn,mx)} ${unit} x ${round(wt)} kg ${scalar}`};}if(['mcg/kg/min','mg/kg/min','units/kg/min'].includes(unit)&&wt){const u=unit.replace('/kg','');const a=mn*wt,b=mx*wt;return{scalar,text:`${rangeText(a,b)} ${u}`,rounded:`${practicalRange(a,b,u)} ${u}`,math:`${rangeText(mn,mx)} ${unit} x ${round(wt)} kg ${scalar}`};}if(['mg/kg/hr','mcg/kg/hr','units/kg/hr'].includes(unit)&&wt){const u=unit.replace('/kg','');const a=mn*wt,b=mx*wt;return{scalar,text:`${rangeText(a,b)} ${u}`,rounded:`${practicalRange(a,b,u)} ${u}`,math:`${rangeText(mn,mx)} ${unit} x ${round(wt)} kg ${scalar}`};}if(unit.includes('fixed')){return{scalar:'Fixed',text:`${rangeText(mn,mx)} ${outUnit(unit)}`,rounded:`${practicalRange(mn,mx,outUnit(unit))} ${outUnit(unit)}`,math:'fixed dose; no weight scaling'};}return{scalar:scalar||'Reference',text:dose.label||'',rounded:dose.label||'',math:'reference text'};}
function calcDrug(drug,p){const override=$('scalarOverride').value;const d=(drug.doses||[])[0];return d?calcOne(d,p,override):{scalar:'',text:'',rounded:'',math:''};}
function flags(drug,p){const text=JSON.stringify(drug).toLowerCase();const f=[];if((p.frail||p.age>=70)&&/(elder|frail|geriatric|delirium|sedation|opioid|benzodiazepine|hypnotic)/.test(text))f.push('frail/elderly');if((p.shock||p.ef<40)&&/(shock|cardiac|heart failure|lv|negative inotropy|bradycardia|tachycardia|ischemia|pressor|vasodilation)/.test(text))f.push('cardiac/shock');if(p.osa&&/(respiratory|osa|ohs|sedation|opioid|apnea|hypoventilation|airway)/.test(text))f.push('OSA/OHS');if(p.qt&&/(qt|ondansetron|droperidol|haloperidol|methadone|amiodarone|antiemetic)/.test(text))f.push('QT');if(p.mh&&/(sevoflurane|desflurane|isoflurane|succinylcholine|volatile|mh trigger|malignant hyperthermia)/.test(text))f.push('MH');if((p.renal!=='normal'||p.crcl<60)&&/(renal|kidney|nephro|metabolite|clearance|esrd|ckd|dialysis)/.test(text))f.push('renal');if(p.hepatic!=='normal'&&/(hepatic|liver|cyp|metabolism|failure)/.test(text))f.push('hepatic');if(p.pregnant&&/(pregnan|ob|uter|fetal|neonate|placenta|tocolysis)/.test(text))f.push('pregnancy/OB');if(p.neuraxial&&/(heparin|anticoag|antiplatelet|aspirin|cangrelor|bivalirudin|coagulation)/.test(text))f.push('neuraxial anticoag');return[...new Set(f)];}
function categoryList(){return[...new Set(DRUGS.map(d=>d.displayClass||d.category).filter(Boolean))].sort();}
function badge(text){const cls=CLASS_COLORS[text]||'other';return`<span class="pill ${cls}">${esc(text)}</span>`;}
function routeText(drug){return[...new Set((drug.doses||[]).map(d=>d.route||'').filter(Boolean))].join(', ');}
function doseText(drug){return(drug.doses||[]).map(d=>`${d.name||'Dose'}: ${d.label}`.replace(/^Adult: /,'')).join('\n');}
function classMoa(drug){const group=drug.displayClass||drug.category;return`${badge(group)}<br><span class="small">${esc(drug.moa)}</span>`;}
function renderMetrics(p){const metrics=[['BMI',p.bmi],['IBW kg',p.ibw],['LBW kg',p.lbw],['AdjBW kg',p.adjbw],['BSA m2',p.bsa],['CG CrCl',p.crcl]];$('metrics').innerHTML=metrics.map(([k,v])=>`<div class="metric">${esc(k)}<br><b>${round(v)}</b></div>`).join('');const warnings=[];if(p.bmi>=30)warnings.push('Obesity flag: review each drug scalar. ABW, IBW, LBW, and AdjBW are not interchangeable.');if(p.crcl<60||p.renal!=='normal')warnings.push('Renal flag: active metabolites, aminoglycosides, NMB duration, anticoagulants, and electrolytes require verification.');if(p.ef<40||p.shock)warnings.push('Cardiac/shock flag: induction dose and vasodilators should be titrated carefully.');if(p.qt)warnings.push('QT flag: review methadone, ondansetron, droperidol, haloperidol, amiodarone, and electrolyte strategy.');if(p.mh)warnings.push('MH flag: volatile agents and succinylcholine are highlighted.');$('caseWarnings').innerHTML=warnings.map(w=>`<div class="case-warning">${esc(w)}</div>`).join('');}
function filteredDrugs(){const p=patient();const q=$('search').value.trim().toLowerCase();const cat=$('category').value;const mode=$('displayMode').value;let out=[];
DRUGS.forEach((drug,idx)=>{const fl=flags(drug,p);const hay=JSON.stringify(drug).toLowerCase();const group=drug.displayClass||drug.category;const scalars=(drug.doses||[]).map(d=>d.scalar||drug.defaultScalar||'').join(' ');if(cat!=='all'&&group!==cat)return;if(q&&!hay.includes(q))return;if(mode==='flagged'&&fl.length===0)return;if(mode==='weight'&&!/(ABW|IBW|LBW|AdjBW)/.test(scalars))return;if(mode==='fixed'&&!/(Fixed)/.test(scalars))return;if(mode==='audit'&&!/audit|placeholder|not verified|starter/i.test(`${drug.sourceStatus} ${drug.millerPage}`))return;out.push({drug,idx,fl,calc:calcDrug(drug,p)});});return out;}
function renderTabs(){const tabs=['all',...categoryList()];$('classTabs').innerHTML=tabs.map(c=>`<button class="tab ${currentCategory===c?'active':''}" data-cat="${esc(c)}">${esc(c==='all'?'All classes':c)}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{currentCategory=b.dataset.cat;$('category').value=currentCategory;render();}));}
function renderGrid(rows){const tbody=$('drugTable').querySelector('tbody');tbody.innerHTML='';visibleRows=[];rows.forEach((r,i)=>{const drug=r.drug,calc=r.calc,fl=r.fl,group=drug.displayClass||drug.category;visibleRows.push({idx:r.idx+1,drug,calc,fl});const tr=document.createElement('tr');if(fl.length)tr.className='row-flagged';tr.innerHTML=`<td class="tbody-pin1">${r.idx+1}</td><td class="tbody-pin2"><button class="drug-button" data-id="${esc(drug.id)}"><span class="drug-name">${esc(drug.name)}</span></button><div class="tagline">${drug.common?badge('Common'):''}</div></td><td>${classMoa(drug)}</td><td>${esc(drug.stage||'')}<br><span class="small">${esc(routeText(drug))}</span></td><td>${esc(drug.concentrations||'')}</td><td class="dose">${esc(doseText(drug))}</td><td><b>${esc(calc.scalar)}</b></td><td class="calc">${esc(calc.text)}</td><td class="rounded">${esc(calc.rounded)}</td><td class="math">${esc(calc.math)}</td><td>${esc(drug.pediatricDosing)}</td><td>${esc(drug.timingSummary||drug.onsetPeak||drug.duration)}</td><td>${esc(drug.metabolismElimination||`${drug.metabolism||''} ${drug.excretion||''}`)}</td><td>${esc(drug.obesityConsiderations)}</td><td>${fl.length?fl.map(x=>`<span class="flag">${esc(x)}</span>`).join(''):'<span class="muted">none</span>'}</td><td>${esc([drug.cautions,drug.contraindications].filter(Boolean).join(' | '))}</td><td>${esc(drug.millerRef)}<br><span class="muted small">${esc(drug.millerPage)}; ${esc(drug.sourceStatus)}</span></td>`;tbody.appendChild(tr);});document.querySelectorAll('.drug-button').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.id)));}
function updateCounts(rows){const p=patient();let flagTotal=0;DRUGS.forEach(d=>{if(flags(d,p).length)flagTotal++;});$('visibleCount').textContent=rows.length;$('totalCount').textContent=DRUGS.length;$('flagCount').textContent=flagTotal;}
function renderCommonWorkflow(){const p=patient();const common=DRUGS.map((drug,idx)=>({drug,idx,fl:flags(drug,p),calc:calcDrug(drug,p)})).filter(r=>r.drug.common);const groups={};common.forEach(r=>{const s=r.drug.stage||'Other/rescue';(groups[s]||(groups[s]=[])).push(r);});let html='<div class="cards">';STAGE_ORDER.filter(s=>groups[s]).forEach(stage=>{const rows=groups[stage];html+=`<section class="stage-card"><div class="cluster-title"><h3>${esc(stage)}</h3><span class="cluster-count">${rows.length} meds</span></div><table class="mini-table"><thead><tr><th>Drug</th><th>Rounded patient dose</th><th>Adult reference</th></tr></thead><tbody>`;rows.forEach(r=>{html+=`<tr><td><button class="drug-button" data-id="${esc(r.drug.id)}">${esc(r.drug.name)}</button><br>${badge(r.drug.displayClass||r.drug.category)}</td><td class="rounded">${esc(r.calc.rounded)}</td><td>${esc(doseText(r.drug))}</td></tr>`;});html+='</tbody></table></section>';});html+='</div>';$('subpage').innerHTML=html;$('subpage').classList.add('active');$('gridWrap').classList.add('view-hidden');$('filters').classList.add('view-hidden');$('classTabs').classList.add('view-hidden');visibleRows=common;updateCounts(common);document.querySelectorAll('.drug-button').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.id)));}
function renderPediatric(){const p=patient();const rows=DRUGS.map((drug,idx)=>({drug,idx,fl:flags(drug,p),calc:calcDrug(drug,p)})).filter(r=>r.drug.pediatricDosing&& !/not yet curated/i.test(r.drug.pediatricDosing));let html='<section class="info-card"><h3>Pediatric dosing subpage</h3><p>This page intentionally separates pediatric information from the adult live-dose grid. Pediatric fields remain source-audit placeholders unless specifically curated.</p></section><br><table class="mini-table"><thead><tr><th>Drug</th><th>Class</th><th>Pediatric dosing</th><th>Timing</th><th>Source status</th></tr></thead><tbody>';rows.forEach(r=>{html+=`<tr><td><button class="drug-button" data-id="${esc(r.drug.id)}">${esc(r.drug.name)}</button></td><td>${badge(r.drug.displayClass||r.drug.category)}</td><td class="peds-dose">${esc(r.drug.pediatricDosing)}</td><td>${esc(r.drug.timingSummary||'')}</td><td>${esc(r.drug.sourceStatus||'')}</td></tr>`;});html+='</tbody></table>';$('subpage').innerHTML=html;$('subpage').classList.add('active');$('gridWrap').classList.add('view-hidden');$('filters').classList.add('view-hidden');$('classTabs').classList.add('view-hidden');visibleRows=rows;updateCounts(rows);document.querySelectorAll('.drug-button').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.id)));}
function renderRegional(){const p=patient();const rows=DRUGS.map((drug,idx)=>({drug,idx,fl:flags(drug,p),calc:calcDrug(drug,p)})).filter(r=>/(Local anesthetic|Regional adjunct)/.test(r.drug.displayClass||r.drug.category));let html='<div class="regional-note"><b>Concentration conversion:</b> 1% local anesthetic = 10 mg/mL. Therefore 0.25% = 2.5 mg/mL, 0.5% = 5 mg/mL, 0.75% = 7.5 mg/mL, and 2% = 20 mg/mL.</div><table class="mini-table"><thead><tr><th>Drug</th><th>Concentrations and mg/mL</th><th>Adult dose / max</th><th>Patient calculated max or dose</th><th>Timing</th><th>Cautions</th></tr></thead><tbody>';rows.forEach(r=>{html+=`<tr><td><button class="drug-button" data-id="${esc(r.drug.id)}">${esc(r.drug.name)}</button><br>${badge(r.drug.displayClass||r.drug.category)}</td><td>${esc(r.drug.concentrations||'')}</td><td>${esc(doseText(r.drug))}</td><td class="rounded">${esc(r.calc.rounded)}</td><td>${esc(r.drug.timingSummary||'')}</td><td>${esc([r.drug.cautions,r.drug.contraindications].filter(Boolean).join(' | '))}</td></tr>`;});html+='</tbody></table>';$('subpage').innerHTML=html;$('subpage').classList.add('active');$('gridWrap').classList.add('view-hidden');$('filters').classList.add('view-hidden');$('classTabs').classList.add('view-hidden');visibleRows=rows;updateCounts(rows);document.querySelectorAll('.drug-button').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.id)));}
function renderVolatile(){const p=patient();const vols=DRUGS.filter(d=>(d.displayClass||d.category)==='Volatile/inhaled');let html='<div class="cards">';vols.forEach(d=>{const dose=(d.doses||[]).find(x=>x.unit==='MAC_age');if(!dose)return;const mac=macAge(Number(dose.min),p.age);html+=`<section class="mac-card"><h3>${esc(d.name)}</h3>${badge('Volatile/inhaled')}<table class="mini-table mac-table"><tbody><tr><td>MAC40 reference</td><td>${round(dose.min)}%</td></tr><tr><td>Patient age</td><td>${round(p.age)} yr</td></tr><tr><td>0.5 MAC</td><td class="mac-value">${round(mac*0.5)}% ET</td></tr><tr><td>0.7 MAC</td><td class="mac-value">${round(mac*0.7)}% ET</td></tr><tr><td>1.0 MAC</td><td class="mac-value">${round(mac)}% ET</td></tr><tr><td>1.3 MAC</td><td class="mac-value">${round(mac*1.3)}% ET</td></tr></tbody></table><p class="small">${esc(d.obesityConsiderations||'')}</p><p class="small">${esc(d.cautions||'')}</p></section>`;});html+='</div>';$('subpage').innerHTML=html;$('subpage').classList.add('active');$('gridWrap').classList.add('view-hidden');$('filters').classList.add('view-hidden');$('classTabs').classList.add('view-hidden');const rows=vols.map((drug,idx)=>({drug,idx,fl:flags(drug,p),calc:calcDrug(drug,p)}));visibleRows=rows;updateCounts(rows);}
function render(){const p=patient();renderMetrics(p);document.querySelectorAll('.page-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));$('subpage').innerHTML='';$('subpage').classList.remove('active');$('gridWrap').classList.remove('view-hidden');$('filters').classList.remove('view-hidden');$('classTabs').classList.remove('view-hidden');if(currentView==='commonWorkflow')return renderCommonWorkflow();if(currentView==='pediatric')return renderPediatric();if(currentView==='regional')return renderRegional();if(currentView==='volatile')return renderVolatile();currentCategory=$('category').value;const rows=filteredDrugs();renderGrid(rows);updateCounts(rows);renderTabs();}
function openDrawer(id){const drug=DRUGS.find(d=>d.id===id);if(!drug)return;const p=patient(),calc=calcDrug(drug,p),fl=flags(drug,p),group=drug.displayClass||drug.category;$('drawerContent').innerHTML=`<h2>${esc(drug.name)}</h2><div class="detail-grid"><div>Class</div><div>${badge(group)} ${drug.common?badge('Common'):''}</div><div>Workflow stage</div><div>${esc(drug.stage||'')}</div><div>MOA</div><div>${esc(drug.moa)}</div><div>Concentration / formulation</div><div>${esc(drug.concentrations||'')}</div><div>General adult dosing</div><div class="dose">${esc(doseText(drug))}</div><div>Patient dose</div><div class="calc">${esc(calc.text)}</div><div>Rounded dose</div><div class="rounded">${esc(calc.rounded)}</div><div>Dose math</div><div class="math">${esc(calc.math)}</div><div>Pediatric dosing</div><div>${esc(drug.pediatricDosing)}</div><div>Timing</div><div>${esc(drug.timingSummary||drug.onsetPeak||drug.duration)}</div><div>Metabolism / elimination</div><div>${esc(drug.metabolismElimination||'')}</div><div>Obesity considerations</div><div>${esc(drug.obesityConsiderations)}</div><div>Flags</div><div>${fl.length?fl.map(x=>`<span class="flag">${esc(x)}</span>`).join(''):'none'}</div><div>Cautions</div><div>${esc(drug.cautions)}</div><div>Contraindications</div><div>${esc(drug.contraindications)}</div><div>Source</div><div>${esc(drug.millerRef)}<br>${esc(drug.millerPage)}<br>${esc(drug.sourceStatus)}</div></div>`;$('drawer').classList.remove('hidden');}
function exportCSV(){const rows=[['#','Drug','Class','Stage','Route','Concentration','General dose','Scalar','Patient dose','Rounded dose','Calculation','Pediatric dosing','Timing','Metabolism/elimination','Obesity/special','Flags','Cautions/contraindications','Source']];visibleRows.forEach((r,i)=>{const drug=r.drug,calc=r.calc||calcDrug(drug,patient()),fl=r.fl||flags(drug,patient());rows.push([r.idx?r.idx+1:i+1,drug.name,drug.displayClass||drug.category,drug.stage,routeText(drug),drug.concentrations,doseText(drug),calc.scalar,calc.text,calc.rounded,calc.math,drug.pediatricDosing,drug.timingSummary,drug.metabolismElimination,drug.obesityConsiderations,fl.join('; '),[drug.cautions,drug.contraindications].filter(Boolean).join(' | '),drug.millerRef]);});downloadText(rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),'periop_drug_grid_visible_v4.csv','text/csv');}
function downloadText(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
function setDefaultPatient(){$('age').value=40;$('sex').value='male';$('height').value=193;$('weight').value=100;$('scr').value=1.0;$('ef').value=60;$('renal').value='normal';$('hepatic').value='normal';['frail','osa','pregnant','qt','mh','shock','neuraxial'].forEach(id=>$(id).checked=false);}
function setup(){$('category').innerHTML='<option value="all">all classes</option>'+categoryList().map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('category').value='all';document.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',render));document.querySelectorAll('.page-tab').forEach(b=>b.addEventListener('click',()=>{currentView=b.dataset.view;render();}));$('clearFilters').addEventListener('click',()=>{$('search').value='';$('category').value='all';$('displayMode').value='all';$('scalarOverride').value='asWritten';currentCategory='all';render();});$('exportCsv').addEventListener('click',exportCSV);$('exportJson').addEventListener('click',()=>downloadText(JSON.stringify(DRUGS,null,2),'periop_drug_database_v4.json','application/json'));$('resetCase').addEventListener('click',()=>{setDefaultPatient();render();});$('closeDrawer').addEventListener('click',()=>$('drawer').classList.add('hidden'));$('drawer').addEventListener('click',e=>{if(e.target.id==='drawer')$('drawer').classList.add('hidden');});render();}
setup();
